version: '3'

vars:
  APP: jgitra
  MODULE:
    sh: go list -m
  VERSION: v0.2.0
  LDFLAGS: >-
    -X {{.MODULE}}/internal/config.Version={{.VERSION}}
    -X {{.MODULE}}/internal/config.App={{.APP}}
  GOEXE:
    sh: go env GOEXE
  APP_BIN: "{{.ROOT_DIR}}/bin/{{.APP}}{{.GOEXE}}"
  CMD: "{{.ROOT_DIR}}/cmd"
  # tools versions
  GOLANGCI_LINT_VERSION: v2.12.2

tasks:
  install:golangci-lint:
    desc: Install golangci-lint
    env:
      GOBIN: "{{.ROOT_DIR}}/bin"
    cmds:
      - >
        go install 
        github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
    status:
      - bin/golangci-lint --version
    silent: true

  lint:
    desc: Check code for vulnerabilities and errors
    deps:
      - install:golangci-lint
    cmds:
      - bin/golangci-lint run
    silent: true

  build:
    desc: Build {{.APP}}
    cmds:
      - >
        go build
        -ldflags="{{.LDFLAGS}}"
        -o {{.APP_BIN}}
        {{.CMD}}/{{.APP}}
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.APP_BIN}}"
    silent: true

  run:
    desc: Build and run {{.APP}}
    deps:
      - build
    cmds:
      - "{{.APP_BIN}} {{.CLI_ARGS}}"
    silent: true

  run:no-compile:
    desc: Run {{.APP}} without compiling to binary
    cmds:
      - >
        go run
        -ldflags="{{.LDFLAGS}}"
        {{.CMD}}/{{.APP}}
        {{.CLI_ARGS}}
    silent: true

  clean:
    desc: Clean output from build
    cmds:
      - go clean
      - >
        go run 
        -ldflags="{{.LDFLAGS}}" 
        -tags clean
        {{.CMD}}/tools/clean
    silent: true
